gridsingularity/component-library

- .babelrc
- .eslintrc
- .gitignore
- .npmignore
- .sass-lint.yml
- .storybook/config.js
- .storybook/webpack.config.js
- lib/components/Button/Button.js
- lib/components/Button/Button.scss
- lib/index.js
- lib/styles/main.scss
- lib/styles/themes.scss
- lib/styles/themify.scss
- package.json
- stories/Test.js
**What / Why**:  Setting up the basic configuration with storybook. Also showing how to implement theming on a button example.
> Setup Base

- .babelrc
- lib/components/Button/Button.js
- lib/components/Themeprovider/Themeprovider.js
- lib/index.js
- package.json
- stories/Button.js
**What / Why**: Create Themeprovider component for easy themeing
> Theme Provider

- README.md
g**Who**: @lelith
**What / Why**:  Update Readme file to help others understand how to work with this repository
> Explain how to work with this repository

- .eslintrc
- .storybook/config.js
- .storybook/style.css
- package.json
- stories/Button.js
**What / Why**:  to show more information about the component and how to use it.
> add decorator and component information

- lib/components/Slider/Slider.scss
- lib/components/Slider/SliderComp.js
- lib/index.js
- package.json
- stories/Slider.js
**What / Why**: Setup new slider component based on rc-slider component from react-components.
> New Component: Slider

- .storybook/webpack.config.js
- README.md
- lib/components/Button/Button.js
- lib/components/Slider/SliderComp.js
- package.json
- stories/Button.js
- stories/Slider.js
**What / Why**: The watcher that was needed for updating and reloading the components did put on heavy load on the browser and cpu. Therefore i refactored the way the css and scss files get required.
> Refactor and improve build process

- lib/components/NumberPicker/NumberPicker.js
- lib/components/NumberPicker/NumberPicker.scss
- lib/index.js
- package.json
- stories/NumberPicker.js
Add new `NumberPicker` component to be used in the [Verbund Stromhandel](https://gridsingularity.atlassian.net/wiki/spaces/D3A/pages/16547871/Salzburg+AG+Verbund) app
> Feat/NumberPicker: Add new component and stories

- lib/components/Slider/SliderComp.js
- package.json
- stories/Slider.js
**What / Why**: Show callback functionalities in Styleguide so consumer does not have to check rc-slider components documentation for basic functionality.
> Expose and show Callbacks of Slider component

- .eslintrc
- lib/components/Button/Button.js
- lib/components/NumberPicker/NumberPicker.js
- lib/components/Slider/SliderComp.js
**What / Why**:  Increase readability of dynamic request of style files
> chore(dynamic request): change into single line command

- .sass-lint.yml
- lib/components/Button/Button.js
- lib/components/Button/Button.scss
- lib/styles/fonts.scss
- lib/styles/themes.scss
- lib/styles/themify.scss
- stories/Button.js
- stories/Slider.js
**What / Why**:  setup theme for d3a
> D3ASIM-151 basic component setup

- lib/components/Headline/Headline.js
- lib/components/Headline/Headline.scss
- lib/index.js
- lib/styles/base.scss
- lib/styles/themes.scss
- stories/Headline.js
**What / Why**:  Setup basic components and classes for typography and headlines
depending on https://github.com/gridsingularity/component-library/pull/16
> D3ASIM-165 Typografie and Headlines

- .sass-lint.yml
- lib/components/Button/Button.scss
- lib/components/Table/Table.js
- lib/components/Table/Table.scss
- lib/components/Table/TableBody.js
- lib/components/Table/TableCell.js
- lib/components/Table/TableFooter.js
- lib/components/Table/TableHeader.js
- lib/components/Table/TableHeaderCell.js
- lib/components/Table/TableRow.js
- lib/index.js
- stories/Table.js
**What / Why**:  Setup table component
> D3ASIM-168 Table component

- package.json
Contains new components and styles for D3A Simulation
- Layout
- Headline and typography styles
- Table
Also some refactorings about the organisation of the demo and some refactorings for the css
> New Release 0.2.0

- lib/components/Navigation/Navigation.js
- lib/components/Navigation/Navigation.scss
- lib/index.js
- stories/Header.js
- stories/Hero.js
- stories/Navigation.js
**What / Why**: Setup basic navigation component
> D3ASIM-200 basic navigation

- lib/components/Navigation/Navigation.js
- package.json
**What / Why**: styles must be required dynamically to work in different enviornments
> Fix wrong require path

- lib/components/Headline/Headline.js
- lib/components/Layout/Layout.js
- package.json
- stories/Headline.js
**What / Why**:  Assignment of prop was wrong.
> fix(Headline): Assign className prop

- lib/components/Button/Button.scss
- lib/components/Table/Table.scss
- lib/styles/base.scss
- lib/styles/themes.scss
- package-lock.json
- package.json
- stories/Card.js
- stories/Hero.js
- stories/Table.js
Style updates needed for https://gridsingularity.atlassian.net/browse/D3ASIM-213
> D3ASIM-213 Feat: Extend table styles

- lib/components/Button/Button.scss
- lib/styles/base.scss
- lib/styles/themes.scss
**What / Why**: Apply hover color to links acording to design
> Fix D3ASIM-210 : some colors are still off

- lib/styles/themes.scss
- package.json
Small fix/update of table border color according to design
> D3ASIM-213 Fix/Tables: Update border-color

- lib/components/Layout/Layout.scss
- lib/components/Tooltip/Tooltip.js
- lib/components/Tooltip/Tooltip.scss
- lib/index.js
- lib/styles/layouts/results.scss
- lib/styles/themes.scss
- lib/styles/typography.scss
- package.json
- stories/Tooltip.js
**What / Why**:  Create static Tooltip component.
> Create static tooltip component

- lib/components/Button/Button.js
- lib/components/Button/Button.scss
- lib/styles/themes.scss
- stories/Button.js
**What / Why**:  Update design of secondary button regarding to the design and create a new button type cta (call to action)
New call to action button type:
Old design of secondary button:
New design of the secondary button:
> D3ASIM-253 Update buttons

- lib/components/Button/Button.scss
- lib/components/Card/Card.js
- lib/components/Card/Card.scss
- lib/components/Card/CardHeader.js
- lib/components/Card/CardHeadline.js
- lib/components/Card/CardMeta.js
- lib/components/Layout/Layout.scss
- lib/components/List/List.js
- lib/components/List/List.scss
- lib/components/List/ListElement.js
- lib/components/Table/Table.scss
- lib/components/Tooltip/Tooltip.js
- lib/components/Tooltip/Tooltip.scss
- lib/index.js
- lib/styles/base.scss
- lib/styles/layouts/frontpage.scss
- lib/styles/layouts/results.scss
- lib/styles/themes.scss
- lib/styles/typography.scss
- package.json
- stories/Card.js
- stories/List.js
- stories/Table.js
- stories/Tooltip.js
**What / Why**:  Applies latest design changes.
> D3ASIM-261 Design QA

- lib/components/Button/Button.js
- package.json
**What / Why**: CTA was not added to allowed types of Buttons
> Fix button allowed types

- lib/styles/layouts/results.scss
- package-lock.json
- package.json
- stories/ResultsPage.js
**What / Why**:  provides another grid place for a 5th graph and adjusts the height of the container contents.
> D3ASIM-300 update layout styles for results page in d3a simulation

- lib/components/Card/Card.scss
- lib/components/List/List.scss
- lib/components/Table/Table.scss
- lib/styles/base.scss
- lib/styles/themes.scss
- lib/styles/typography.scss
- package-lock.json
- package.json
- stories/List.js
- stories/Tooltip.js
**What / Why**:  Update colors and font-weights according to the design
> D3ASIM-312 update colors and fontweights

- lib/components/Table/Table.scss
- lib/styles/base.scss
- lib/styles/themes.scss
- package.json
**What / Why**:  regarding to the feedback yesterday the font-sizes needed to be bigger and the font brighter for better readability during the beamer presentation
> Increase readabilty for beamer presentation

- README.md
- package.json
**What / Why**:  Enable deployment of static build of the storybook to heroku.
> Setup deployment of styleguide to heroku

- README.md
- lib/components/NumberPicker/NumberPicker.js
- lib/components/NumberPicker/NumberPicker.scss
- lib/styles/themes.scss
- package.json
- stories/NumberPicker.js
**What / Why**: applies d3a specific style to the number picker component.
> D3ASIM-105 style number picker component

- lib/components/Select/Select.js
- lib/components/Select/Select.scss
- lib/components/TextInputField/TextInputField.js
- lib/components/TextInputField/TextInputField.scss
- lib/images/icon_arrow_down.svg
- package.json
- stories/Select.js
- stories/TextInputField.js
**What / Why**:  Updates Select and TextInput form fields. 
- Available in two sizes
- updates the color on the select arrow.
before: 
after:
> Style updates for form fields

- .editorconfig
- lib/components/NumberPicker/NumberPicker.js
- lib/components/NumberPicker/NumberPicker.scss
- stories/NumberPicker.js
- align sizing with other form fields via kind property
- update examples
> Update number picker

- .travis.yml
- README.md
- lib/components/Button/dummy.test.js
- package-lock.json
- package.json
**What / Why**:  Uses now semantic-release package to handle package versioning and publishing to npm
> D3ASIM-472 Chore(deployment): Optimize deployment

- .babelrc
- .eslintrc
- lib/components/TextInputField/TextInputField.scss
- lib/components/TreeView/TreeLeaf.js
- lib/components/TreeView/TreeTitle.js
- lib/components/TreeView/TreeView.js
- lib/components/TreeView/TreeView.scss
- package-lock.json
- package.json
- stories/Configuration.js
- stories/TextInputField.js
**Who**: @lelith, @cfleschhut 
**What / Why**: Refactors the leaf title element. As the title shall be editable it will render now as an input field instead of a span when the property "editable" is true. It accepts an onChange event.
> D3ASIM-496 refactor leaf title 

- lib/components/Switch/Switch.js
- lib/components/Switch/Switch.scss
- lib/images/icon_check.svg
- lib/index.js
- lib/styles/themes.scss
- stories/Switch.js
**What / Why**:  Creates new component for check-box styled as a switch
normal state checked and unchecked
hover state:
> D3ASIM-492 Switch Component

- lib/components/Dialog/Dialog.js
- lib/components/Dialog/Dialog.scss
- lib/index.js
- stories/Dialog.js
**What / Why**:  dismisable dialog component
> D3ASIM-505:  new component Dialog

- lib/components/Layout/layouts/configuration.scss
- lib/components/StepButton/StepButton.js
- lib/components/StepButton/StepButton.scss
- lib/images/icon_left_double_angle.svg
- lib/images/icon_right_double_angle.svg
- lib/index.js
- stories/Configuration.js
**What / Why**:  creates a navigational element with arrows to left or right and updates the configuration-scenario page 2 layout.
this resolves https://gridsingularity.atlassian.net/browse/D3ASIM-508
hover state:
> D3ASIM-508 back button

- lib/components/Range/RangeComp.js
- lib/components/Slider/Slider.scss
- lib/index.js
- lib/styles/themes.scss
- stories/Range.js
**What / Why**:  sets up new higher order component for range-slider based on rc-slider. Applies styles from d3a Design.
> D3ASIM-493 range slider component and style

- lib/components/Layout/layouts/configuration.scss
- stories/Configuration.js
**What / Why**:  changes the layout of configuration-scenario to fit in the other elements of the page.
before 
after
> D3ASIM-508 configuration scenario layout

- lib/components/Layout/layouts/configuration.scss
- lib/components/TreeView/TreeView.scss
- stories/Configuration.js
**What / Why**: in some cases the tree lines have not been drawn correctly. resolves https://gridsingularity.atlassian.net/browse/D3ASIM-522
before:
after:
> D3ASIM-522 fix the tree lines

- lib/components/Button/Button.js
- lib/components/Button/Button.scss
- stories/Button.js
**What / Why**:  new Button Variation for a Icon-Button with label underneath. E.g. for control Buttons Also unifies the Button shadows and hover styles to fit the other form elements. 
Hover & Active state
> D3ASIM-536 New Button varant: icon button

- README.md
BREAKING CHANGE: icon styles did change and will therefore break current icon usage
> fix(readme): add badges and links to material io

- lib/components/PopOutMenu/PopOutMenu.js
With the `FiniteDieselGenerator`
* https://gridsingularity.atlassian.net/browse/D3ASIM-535
* https://github.com/gridsingularity/d3a-web/pull/100
* https://github.com/gridsingularity/d3a/pull/199
being added as a new type of `generator` we need to output `key`s for each item in the PopOutMenu list that are still unique
⚠️ **Required for https://github.com/gridsingularity/d3a-ui/pull/111**
> D3ASIM-535 Fix/PopOutMenu list items: Output unique key for each item

- stories/_Verbund/IntroPage.js
Feature : Verbund Theme development
- Added Theme called `verbund`
- Added Components for `intro-page`
- Added Stories for Components and Intro Page
> feat(verbund): intro page components

- lib/components/PopOutMenu/PopOutMenu.js
- lib/components/TreeView/TreeLeaf.js
**What/Why**
fixes two warnings
> Fix warnings

- README.md
One more test (and waiting until travis job has fully finished successfully)
> chore(npm-package-publishing): testing semantic-release automatic publishing

- lib/components/Dialog/Dialog.js
- lib/components/PopOutMenu/PopOutMenu.js
- lib/components/TreeView/TreeLeaf.js
Resolves https://gridsingularity.atlassian.net/browse/D3ASIM-625
Follow-up fix to changes added in https://github.com/gridsingularity/component-library/pull/86
> D3ASIM-625 Fix/Configuration tree: Device dialog not being displayed in the UI configuration tree

- lib/components/Diamond/Diamond.scss
- lib/components/Layout/layouts/configuration.scss
- lib/components/ProgressIndicator/IndicatorItem.js
- lib/components/ProgressIndicator/ProgressIndicator.js
- lib/components/ProgressIndicator/ProgressIndicator.scss
- lib/index.js
- stories/Configuration.js
- stories/ProgressIndicator.js
- stories/img/icon_chart.svg
- stories/img/icon_grid.svg
**What / Why**: This component helps users to orient and navigate trough a several step process. So they understand how many more steps are ahead of them and also is usable as a navigation trough the steps.
hover-state:
> D3ASIM-584 new component progress indicator
